Resources:
  Tasks:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: tasks
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ConfigWorkerSQS:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "ConfigWorkerSQS"

  CommandWorkerSQS:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "CommandWorkerSQS"
